sudo: required
services:
    - docker

before_install:
    - docker build -t kekami/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kekami/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: eu-north-1
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-north-1-062367911922"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY